apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: gatewaydev
  name: gatewaydev-external
  namespace: "openfaasdev"
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31212
  selector:
    app: gatewaydev
