---
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: openfaas
    component: prometheus-config
  name: prometheus-config
  namespace: "openfaas"
data:
  prometheus.yml: |
    global:
      scrape_interval:     3s
      evaluation_interval: 3s
      external_labels:
          monitor: 'faas-monitor'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 3s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kubernetes-pods'
        scrape_interval: 3s
        honor_labels: false
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - openfaas
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
